export {default as Navbar} from './Navbar/Navbar'
export {default as Header} from './Header/Header'
export {default as About} from './About/About'
export {default as Menu} from './Menu/Menu'
export {default as Magazine} from './Magazine/Magazine'
export {default as Gallery} from './Gallery/Gallery'
export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'