export {default as Navbar} from './Navbar'
export {default as Header} from './Header'
export {default as About} from './About'
export {default as Menu} from './Menu'
export {default as Megazine} from './Megazine'
export {default as Gallery} from './Gallery'
export {default as Contact} from './Contact'
export {default as Footer} from './Footer'